spring.application.name=ds-evento
spring.datasource.url=${DATABASE.URL}
spring.datasource.username=${DATABASE.USERNAME}
spring.datasource.password=${DATABASE.PASSWORD}

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true